In [30]:
from os import rename

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.ticker as mticker
import importlib
import config
importlib.reload(config)
import pandas_market_calendars as mcal

from config import US_TICKERS_FINAL,US_TICKERS_FINAL_adj,BB_PRICES, BB_PRICES_COMPLETE

In [2]:
#Load tickers file
df = pd.read_csv(US_TICKERS_FINAL)
df.shape
print(df.head())

           ISIN Ticker  Start_Date    End_Date    min_date    max_date  \
0  US8110544025    SSP  05/01/2018  13/06/2025  02/01/2018  28/03/2024
1  US3020811044   EXLS  23/01/2018  24/06/2025  02/01/2018  28/03/2024
2  US46269C1027   IRDM  03/01/2018  17/06/2025  02/01/2018  28/03/2024
3  US63001N1063   NATL  29/01/2024  30/06/2025  02/01/2024  28/03/2024
4  US7580754023    RWT  20/01/2018  12/06/2025  25/07/2018  28/03/2024

                   Sector   bb_tcm alt_bb_tcm   mkt_cap  turnover bb_tcm_note  \
0  Consumer Discretionary   SSP US        NaN  1.254711  5.021609         NaN
1  Information Technology  EXLS US        NaN  2.143838  5.050401         NaN
2  Communication Services  IRDM US        NaN  1.151158  5.090490         NaN
3              Financials  NATL US        NaN  1.613916  5.102278         NaN
4              Financials   RWT US        NaN  1.146697  5.118686         NaN

  mkt_cap_bin turnover_bin
0       1–1.5          5-6
1       2–2.5          5-6
2       1–1.5          5-6
3       1.5–2          5-6
4       1–1.5          5-6

In [4]:
df['Start_Date'] = pd.to_datetime(df['Start_Date'],format='%d/%m/%Y')
df['End_Date'] = pd.to_datetime(df['End_Date'],format='%d/%m/%Y')
df['min_date'] = pd.to_datetime(df['min_date'],format='%d/%m/%Y')
df['max_date'] = pd.to_datetime(df['max_date'],format='%d/%m/%Y')

df.rename(columns={'Start_Date':'start_date_s'}, inplace=True)
df.rename(columns={'End_Date':'end_date_s'}, inplace=True)
df.rename(columns={'min_date':'start_date_px'}, inplace=True)
df.rename(columns={'max_date':'end_date_px'}, inplace=True)

print(df.dtypes)

KeyError: 'Start_Date'

In [13]:
df.drop(columns=['mkt_cap_bin','turnover_bin'], inplace=True)

In [26]:
#create the ticker, from_date and to_date list to pass into BQNT
#pd.tseries.offsets.BDay(1) # adds or minus 1 business day on a datetime object. Might be useful.
df['bb_start_date'] = df['start_date_s']-pd.tseries.offsets.BDay(20)
df['bb_end_date'] = df['end_date_s']+pd.tseries.offsets.BDay(20)

In [27]:
df.to_csv(US_TICKERS_FINAL_adj, index=False)

In [6]:
print(pdf.shape)
print(pdf.dtypes)
print(pdf['px_last'].isna().sum(), 'NaN prices')
print(pdf[pdf['px_last'].isna()][['ISIN','Ticker','date']].head(10))

(3540016, 5)
ISIN                       object
Ticker                     object
resolved_ticker            object
date               datetime64[ns]
px_last                   float64
dtype: object
1459 NaN prices
               ISIN Ticker       date
14404  US35243J1016   FBRT 2021-09-21
14405  US35243J1016   FBRT 2021-09-22
14406  US35243J1016   FBRT 2021-09-23
14407  US35243J1016   FBRT 2021-09-24
14408  US35243J1016   FBRT 2021-09-25
14409  US35243J1016   FBRT 2021-09-26
14410  US35243J1016   FBRT 2021-09-27
14411  US35243J1016   FBRT 2021-09-28
14412  US35243J1016   FBRT 2021-09-29
14413  US35243J1016   FBRT 2021-09-30

In [5]:
pdf = pd.read_csv(BB_PRICES, sep='\t', low_memory=False, dtype={'ISIN': str})

# drop any rows where px_last literally contains the string 'px_last'
pdf = pdf[pdf['px_last'] != 'px_last'].copy()

pdf['px_last'] = pdf['px_last'].astype(float)
pdf['date'] = pd.to_datetime(pdf['date'])
pdf.drop(columns=['Unnamed: 0','row_id'], inplace=True)

In [7]:
#Count of unique ISIN's in the pricing dataframe
pdf['ISIN'].nunique()

1469

In [8]:
#Count of unique ISIN's in the ticker dataframe
df['ISIN'].nunique()

1469

In [9]:
pdf['px_last'].isna().count()

np.int64(3540016)

In [10]:
print(pdf['px_last'].isna().sum(), 'NaN prices')
print(pdf['px_last'].notna().sum(), 'valid prices')
print(pdf.shape[0], 'total rows')

1459 NaN prices
3538557 valid prices
3540016 total rows

In [60]:
pdf['resolved_ticker'][pdf['px_last'].isna()].unique()

array(['FBRT US', 'ALGM US', 'CTKB US', 'RXO US', 'PGNY US', 'ACA US',
       'AIRC US', 'ASO US', 'ESAB US', 'HRMY US', 'FYBR US', 'YETI US',
       'IAA US', 'CNXC US', 'ILPT US', 'HAYW US', 'LTHM US', 'ARLO US',
       'CRSR US', 'SNCY US', 'FTRE US', 'CNM US', 'KNF US', 'KLG US',
       'NVST US', 'NARI US', 'PRVA US', 'WH US', 'SLVM US', 'EHAB US',
       'MCW US', 'ETRN US', 'JXN US', 'GO US', 'DAY US', 'EDR US',
       'SONO US', 'LESL US', 'BJ US', 'GTX US', 'CTVA US', 'SHC US',
       'SLQT US', 'VNT US', 'KTB US', 'CERT US', 'DT US', 'DOCS US',
       'REZI US', 'OGN US', 'ADT US', 'GTM US', 'CHX US', 'DTM US',
       'OTIS US', 'CARR US', 'KD US', 'VSXY US', 'DBX US', 'WBD US',
       'VLTO US', 'GEHC US', 'KVUE US', 'UBER US', 'ABNB US'],
      dtype=object)

In [62]:
pdf[pdf['px_last'].isna()].nunique()

ISIN                65
Ticker              65
resolved_ticker     65
date               904
px_last              0
dtype: int64

In [11]:
dfe1 = (pdf[pdf['px_last'].isna()]
    .groupby('resolved_ticker')['date']
    .agg(min_date='min', max_date='max', nan_count='count')
    .sort_values('nan_count', ascending=False))

In [13]:
dfe1['date_range_days'] = (dfe1['max_date'] - dfe1['min_date']).dt.days + 1

In [17]:
dfe1[dfe1['nan_count']!=dfe1['date_range_days']]

Empty DataFrame
Columns: [min_date, max_date, nan_count, date_range_days]
Index: []

In [22]:
pdf[pdf['resolved_ticker']=='SONO US'].head(50)

                 ISIN Ticker resolved_ticker       date  px_last
3260012  US83570H1086   SONO         SONO US 2018-07-05    15.00
3260013  US83570H1086   SONO         SONO US 2018-07-06    15.00
3260014  US83570H1086   SONO         SONO US 2018-07-07    15.00
3260015  US83570H1086   SONO         SONO US 2018-07-08    15.00
3260016  US83570H1086   SONO         SONO US 2018-07-09    15.00
3260017  US83570H1086   SONO         SONO US 2018-07-10    15.00
3260018  US83570H1086   SONO         SONO US 2018-07-11    15.00
3260019  US83570H1086   SONO         SONO US 2018-07-12    15.00
3260020  US83570H1086   SONO         SONO US 2018-07-13    15.00
3260021  US83570H1086   SONO         SONO US 2018-07-14    15.00
3260022  US83570H1086   SONO         SONO US 2018-07-15    15.00
3260023  US83570H1086   SONO         SONO US 2018-07-16    15.00
3260024  US83570H1086   SONO         SONO US 2018-07-17    15.00
3260025  US83570H1086   SONO         SONO US 2018-07-18    15.00
3260026  US83570H1086   SONO         SONO US 2018-07-19    15.00
3260027  US83570H1086   SONO         SONO US 2018-07-20    15.00
3260028  US83570H1086   SONO         SONO US 2018-07-21    15.00
3260029  US83570H1086   SONO         SONO US 2018-07-22    15.00
3260030  US83570H1086   SONO         SONO US 2018-07-23    15.00
3260031  US83570H1086   SONO         SONO US 2018-07-24    15.00
3260032  US83570H1086   SONO         SONO US 2018-07-25    15.00
3260033  US83570H1086   SONO         SONO US 2018-07-26    15.00
3260034  US83570H1086   SONO         SONO US 2018-07-27    15.00
3260035  US83570H1086   SONO         SONO US 2018-07-28    15.00
3260036  US83570H1086   SONO         SONO US 2018-07-29    15.00
3260037  US83570H1086   SONO         SONO US 2018-07-30    15.00
3260038  US83570H1086   SONO         SONO US 2018-07-31    15.00
3260039  US83570H1086   SONO         SONO US 2018-08-01    15.00
3260040  US83570H1086   SONO         SONO US 2018-08-02    19.91
3260041  US83570H1086   SONO         SONO US 2018-08-03    20.95
3260042  US83570H1086   SONO         SONO US 2018-08-04    20.95
3260043  US83570H1086   SONO         SONO US 2018-08-05    20.95
3260044  US83570H1086   SONO         SONO US 2018-08-06    19.35
3260045  US83570H1086   SONO         SONO US 2018-08-07    19.15
3260046  US83570H1086   SONO         SONO US 2018-08-08    18.14
3260047  US83570H1086   SONO         SONO US 2018-08-09    16.69
3260048  US83570H1086   SONO         SONO US 2018-08-10    18.49
3260049  US83570H1086   SONO         SONO US 2018-08-11    18.49
3260050  US83570H1086   SONO         SONO US 2018-08-12    18.49
3260051  US83570H1086   SONO         SONO US 2018-08-13    17.18
3260052  US83570H1086   SONO         SONO US 2018-08-14    16.86
3260053  US83570H1086   SONO         SONO US 2018-08-15    17.63
3260054  US83570H1086   SONO         SONO US 2018-08-16    17.35
3260055  US83570H1086   SONO         SONO US 2018-08-17    18.45
3260056  US83570H1086   SONO         SONO US 2018-08-18    18.45
3260057  US83570H1086   SONO         SONO US 2018-08-19    18.45
3260058  US83570H1086   SONO         SONO US 2018-08-20    19.42
3260059  US83570H1086   SONO         SONO US 2018-08-21    20.08
3260060  US83570H1086   SONO         SONO US 2018-08-22    21.69
3260061  US83570H1086   SONO         SONO US 2018-08-23    20.83

In [20]:
#Backfill to fix the likely new companies that didn't have a price before their start_date.
pdf['px_last'] = pdf.groupby('resolved_ticker')['px_last'].bfill()

In [21]:
#Check all NaNs are fixed.
print(pdf['px_last'].isna().sum(), 'NaNs remaining after bfill')

0 NaNs remaining after bfill

In [25]:
pdf.rename(columns={'resolved_ticker':'bb_tcm'}, inplace=True)
pdf.dtypes

ISIN               object
Ticker             object
bb_tcm             object
date       datetime64[ns]
px_last           float64
dtype: object

In [28]:
#Send to parquet for better compression and faster loading.
pdf.to_parquet(BB_PRICES_COMPLETE, index=False)